version: '3'  # Docker Composeのバージョン
services:
  web:  # コンテナに名前をつける
    build:
      context: .
      dockerfile: "Dockerfile.dev"
    volumes:
      - .:/app # ホストPCのカレントディレクトリとコンテナ内のcodeディレクトリを同期させる
      - python-packages:/root/.local/share
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000 
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - "dbdata:/var/lib/postgresql/data"
volumes:
  python-packages:
  dbdata:
