# Generated by Django 2.2.6 on 2019-10-13 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitteru', '0002_auto_20191013_0817'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MediaFile',
        ),
    ]
