# Generated by Django 2.2.6 on 2019-10-20 23:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('twitteru', '0005_auto_20191019_0339'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50, null=True)),
                ('self_introduction', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('website', models.URLField()),
                ('tweet_open_flag', models.BooleanField()),
                ('direct_message_flag', models.BooleanField()),
                ('sensitive_flag', models.BooleanField()),
                ('followed_num', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UserSettings',
        ),
    ]
