# Generated by Django 2.2.6 on 2019-10-26 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitteru', '0008_auto_20191023_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='replied_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replied_post', to='twitteru.Post'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='replying_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replying_post', to='twitteru.Post'),
        ),
    ]
